name: fretboard
description: Song writing toolkit for Flutter
version: 0.1.1-dev.1
homepage: https://github.com/mugbug/fretboard
topics:
  - music
  - chord
  - tab
  - scale
  - theory

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>3.10.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  alchemist: ^0.6.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
